(require 'spacelite-ledger)
(require 'spacelite-multi-cursor)
(require 'spacelite-yasnippet)
(require 'spacelite-org)
(require 'spacelite-google)
(require 'spacelite-deft)
(require 'spacelite-treemacs)
(require 'spacelite-evil-easymotion)
(require 'spacelite-string-inflection)
(require 'spacelite-beancount)
(require 'nix-update)

(defun spacelite/init-utils ()
  (spacelite/init-ledger)
  (spacelite/init-multi-cursor)
  (spacelite/init-yasnippet)
  (spacelite/init-org)
  (spacelite/init-google)
  (spacelite/init-deft)
  (spacelite/init-treemacs)
  (spacelite/init-evil-easymotion)
  (spacelite/init-string-inflection)
  )

(provide 'spacelite-utils)
