(require 'spacelite-yasnippet)
(require 'spacelite-org)
(require 'spacelite-google)
(require 'spacelite-deft)
(require 'spacelite-treemacs)
(require 'spacelite-evil-easymotion)

(defun spacelite/init-utils ()
  (spacelite/init-yasnippet)
  (spacelite/init-org)
  (spacelite/init-google)
  (spacelite/init-deft)
  (spacelite/init-treemacs)
  (spacelite/init-evil-easymotion))

(provide 'spacelite-utils)
